### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by arudakiya** [Madrapps/Pikolo#22]
final HSLColorPicker colorPicker = (HSLColorPicker) findViewById(**R.id.colorPicker**);

R.id.colorPicker  :- missing please help me

**Comment by thsaravana** [comment]
I think this is a build error. Try cleaning and then building again. I took a local checkout and it works fine.

**Comment by thsaravana** [comment]
I suppose this is an IDE issue or a build issue that could be resolved using the latest 3.0 IDE or by cleaning the project.
