### ISSUE TITLE
Android Studio 3.14

### ISSUE THREAD

**Issue by TadyTheFish** [Madrapps/Pikolo#26]
I tried using your library in Android studio 3.1.4 and kotlin
i inserted the code you provided and the IDE converts it to kotlin.. this is what I got

val colorPicker = findViewById<HSLColorPicker>(R.id.colorPicker)
        colorPicker.setColorSelectionListener(object : SimpleColorSelectionListener() {
            override fun onColorSelected(color: Int) {
                // Do whatever you want with the color
                //imageView.getBackground().setColorFilter(color, PorterDuff.Mode.MULTIPLY)
            }
        })
The listener does not work I get an null exception. val colorPicker is alway null and I don't know how to fix it. If I change colorPicker.setColorSelectionListener(object : SimpleColorSelectionListener() { to colorPicker?.setColorSelectionListener(object : SimpleColorSelectionListener() { the code compiles but it does not work.
Can you help me?

**Comment by thsaravana** [comment]
It appears that `colorPicker` is null, which means that your Layout doesn't have `R.id.colorPicker` view. You need for first add `HSLColorPicker` to your Layout, like below:

```
<com.madrapps.pikolo.HSLColorPicker
        android:id="@+id/colorPicker"
        android:layout_width="300dp"
        android:layout_height="300dp"
        app:arc_length="110"
        app:hue_start_angle="30"
        app:indicator_radius="18dp"
        app:lightness_start_angle="270"
        app:radius_offset="2dp"
        app:saturation_start_angle="150"/>
```

Once the `colorPicker` view is present in your layout, you can then use `findViewById(R.id.colorPicker)`. Let us know if this fixes your issue.

**Comment by instrap** [comment]
Closing this since this is not an issue with the library.
