### ISSUE TITLE
jitpack release for 2.0.0 - classes missing

### ISSUE THREAD

**Issue by ligi** [Madrapps/Pikolo#37]
all classes are missing in the jar inside the aar

**Comment by thsaravana** [comment]
I gave an immediate fix by reuploading to bintray the fixed version. But I totally forgot about `jitpack`. The problem was I accidentally turned on the `minify` for release. I will patch it in `2.0.1`

**Comment by thsaravana** [comment]
@ligi I checked 2.0.1 and it's patched now. Let me know if you find any other issues. Thanks for reporting this bug 👍
