### ISSUE TITLE
Update the ReadMe 

### ISSUE THREAD

**Issue by thsaravana** [Madrapps/Pikolo#39]
Add the following updates to the README:
1. the fact that 2.0 version will use AndroidX
2. the various xml attributes available to configure the colour picker.

**Comment by ligi** [comment]
in this process also perhaps change `implementation 'com.github.madrapps:pikolo:2.0.0'` as this recomments the broken version. Perhaps just do `<current version>` as it is also in the jitpack badge and so you do not need to update the readme every time
