### ISSUE TITLE
setColor() and getColor()

### ISSUE THREAD

**Issue by manmohan777** [Madrapps/Pikolo#40]
Can any one please tell me how to set and get colour of  the picker using java code ?

**Comment by thsaravana** [comment]
You can take a look at the `sample` app in this repository. Specifically, take a look at this: https://github.com/Madrapps/Pikolo/blob/master/sample/src/main/java/com/madrapps/pickcolor/MainActivity.java

**Comment by manmohan777** [comment]
Is there any way to get colour from color picker on load of the class?

**Comment by thsaravana** [comment]
Could you elaborate your use case? 
Pikolo doesn't have any colour set initially. You could set the colour using `setColor()`. Once the picker is moved, then you will get the color via the `onColorSelected()` callback. There is no `getColor` since this callback will give you the color.

**Comment by manmohan777** [comment]
OK got it.... Thankyou so much for your help.
