### ISSUE TITLE
How to display preview circle?

### ISSUE THREAD

**Issue by nithinmurali** [Madrapps/Pikolo#41]
There is a big circle in the center of view in all the previews, which displays the current color selected. How can I enable it? Trying the sample code did not work. It just shows the color selection wheel without the circle in the center.

```
    <com.madrapps.pikolo.RGBColorPicker
        android:id="@+id/colorPicker"
        android:layout_width="160dp"
        android:layout_height="160dp"
        android:tag="color_select"
        android:layout_marginStart="8dp"

        pikolo:arc_length="110"
        pikolo:red_start_angle="30"
        pikolo:blue_start_angle="270"
        pikolo:green_start_angle="150"
        pikolo:radius_offset="10dp"
        pikolo:indicator_radius="10dp"
        />
```

**Comment by thsaravana** [comment]
I guess the previews are a bit misleading. The circle at the center is not part of the Pikolo view, but just an ImageView to show the output color. You can refer the [sample app's source code](https://github.com/Madrapps/Pikolo/tree/master/sample) to see how it's done. You could easily implement this having both the `RGBColorPicker` and an `ImageView` in a `FrameLayout`.
